<div ng-cloak="" ng-init="loadPage(1)">
    <div class="main-col">

        <section class="content-header"> 
            <h1>Mes campagnes
                <span class="ss-titre">Consultez l'ensemble de vos campagnes</span>
            </h1>  
        </section>
        <section class="content">                     
            <div class="">                          
                <section class=" mgb30 horizontal-menu">                             
                    <ul class="nav nav-tabs nav-pills" id="my-campaings-tab">                              
                        <li class="active">
                            <a href="#campagnes" role="tab" data-toggle="tab">Campagnes</a>
                        </li>                              
                        <li>
                            <a href="#brouillons" role="tab" data-toggle="tab">Brouillons</a>
                        </li>                            
                    </ul>                          
                </section>                    
            </div>                    
            <div class="tab-content">                    
                <div class="tab-pane fade in active" id="campagnes">                    
                    <div class="">                          
                        <section class=" mgb30 filters-campaigns">                             
                            <form class="bs-example bs-example-form" role="form">                                
                                <div class=" input-group-lm col-md-2">                                  
                                    <input type="text" class="form-control" placeholder="Username">                                
                                </div>                                
                                <div class="input-group-lm  col-md-2">                                                                   
                                    <select class="form-control">                                    
                                        <option>Statuts
                                        </option>                                    
                                        <option>option 2
                                        </option>                                    
                                        <option>option 3
                                        </option>                                    
                                        <option>option 4
                                        </option>                                    
                                        <option>option 5
                                        </option>                                  
                                    </select>                                
                                </div>                                
                                <div class="input-group-lm  col-md-2">                                                                   
                                    <select class="form-control">                                    
                                        <option>Créateur
                                        </option>                                    
                                        <option>option 2
                                        </option>                                    
                                        <option>option 3
                                        </option>                                    
                                        <option>option 4
                                        </option>                                    
                                        <option>option 5
                                        </option>                                  
                                    </select>                                
                                </div>                                
                                <div class="input-group-lm  col-md-2">                                                                   
                                    <select class="form-control">                                    
                                        <option>Type de campagne
                                        </option>                                    
                                        <option>option 2
                                        </option>                                    
                                        <option>option 3
                                        </option>                                    
                                        <option>option 4
                                        </option>                                    
                                        <option>option 5
                                        </option>                                  
                                    </select>                                
                                </div>                                                                 
                                <div class="input-group-lm col-md-2">                                                                                 
                                    <div class="input-group">                                            
                                        <div class="input-group-addon">                                                
                                            <i class="fa fa-calendar"></i>                                            
                                        </div>                                            
                                        <input type="text" id="reservation" class="form-control pull-right">                                        
                                    </div>
                                    <!-- /.input group -->                                
                                </div>                                
                                <div class="input-group">                                     
                                    <button type="submit" class="btn btn-primary">
                                        <i class="fa fa-filter"></i> Filtrer
                                    </button>                                     
                                    <a href="" class="btn btn-default">
                                        <i class="fa fa-save"></i> Exporter</a>                                
                                </div>                                                              
                            </form>                          
                        </section>                     
                    </div>                     
                    <div class="">                          
                        <section class="">                                                             
                            <!-- ----------------------START FORM LAST CAMPAINGS-------------------------- -->                                 
                            <div class="box">                                
                                <div class="box-header">                                    
                                    <h3 class="box-title">Liste de mes campagnes</h3>                                                                     
                                </div>
                                <!-- /.box-header -->                                
                                <div class="box-body">                                    
                                    <table class="table table-bordered">                                        
                                        <tbody>
                                            <tr>                                            
                                                <th style="width:40px;">Type</th>                                            
                                                <th>Nom</th>                                            
                                                <th>Liste</th>                                            
                                                <th style="width: 80px">Statut</th>                                            
                                                <th>Prochain envoi</th>                                            
                                                <th>Fin de campagne</th>                                            
                                                <th style="width: 190px">Options</th>                                        
                                            </tr>                                        
                                            <tr ng-repeat="campaign in campaign.list"
                                                ng-class-odd="'odd'"
                                                ng-class-even="'even'"
                                                ng-class="{'canceled':campaign.status === 'canceled'}">                                            
                                                <td class="table-type">
                                                    <i ng-class="{'fa fa-paper-plane-o grey':campaign.automated.status === '1'}" data-toggle="tooltip" data-placement="top" title="Type de campagne"></i></td>                                            
                                                <td ng-bind="campaign.name">
                                                    <a href="#" data-target="#view_campaign" data-toggle="modal">Ma campagne</a></td>                                            
                                                <td ng-bind="campaign.list.contact">-</td>                                            
                                                <td class="table-status" ng-bind="campaign.status">                                               
                                                    <span class="badge bg-green">Confirmée</span>                                            
                                                </td>                                            
                                                <td>XX/XX/XXXX 24:00</td>                                            
                                                <td>XX/XX/XXXX 24:00</td>                                            
                                                <td>                                              
                                                    <div class="btn-group">                                              
                                                        <button type="button" class="btn btn-default">Stopper la campagne
                                                        </button>                                              
                                                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">                                                
                                                            <span class="caret">
                                                            </span>                                                
                                                            <span class="sr-only">Toggle Dropdown
                                                            </span>                                              
                                                        </button>                                              
                                                        <ul class="dropdown-menu" role="menu">                                                
                                                            <li>
                                                                <a href="#">
                                                                    <i class="fa fa-font"> |</i>Renommer</a>
                                                            </li>                                                
                                                            <li>
                                                                <a href="#">
                                                                    <i class="fa fa-times"> |</i>Suprimer</a>
                                                            </li>                                                
                                                            <li class="divider">
                                                            </li>                                                
                                                            <li>
                                                                <a href="#">Special link or info</a>
                                                            </li>                                              
                                                        </ul>                                            
                                                    </div>                                          </td>                                        
                                            </tr>
                                            
                                            <tr>
                                                <td colspan="7"><hr></td>
                                            </tr>







                                            <tr class="canceled">                                            
                                                <td class="table-status">
                                                    <i class="fa fa-calendar grey" data-toggle="tooltip" data-placement="top" title="Type de campagne"></i></td>                                            <td>
                                                    <a href="#" data-target="#view_campaign" data-toggle="modal">Ma campagne</a></td>                                            <td>-</td>                                            
                                                <td class="table-status">                                               
                                                    <span class="badge bg-red">Annulée
                                                    </span>                                            </td>                                            <td>XX/XX/XXXX 24:00</td>                                            <td>XX/XX/XXXX 24:00</td>                                            <td>                                              
                                                    <div class="btn-group">                                              
                                                        <button type="button" class="btn btn-default">Voir les résultats
                                                        </button>                                              
                                                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">                                                
                                                            <span class="caret">
                                                            </span>                                                
                                                            <span class="sr-only">Toggle Dropdown
                                                            </span>                                              
                                                        </button>                                              
                                                        <ul class="dropdown-menu" role="menu">                                                
                                                            <li>
                                                                <a href="#">
                                                                    <i class="fa fa-font"> |</i>Renommer</a>
                                                            </li>                                                
                                                            <li>
                                                                <a href="#">
                                                                    <i class="fa fa-times"> |</i>Suprimer</a>
                                                            </li>                                                
                                                            <li class="divider">
                                                            </li>                                                
                                                            <li>
                                                                <a href="#">Special link or info</a>
                                                            </li>                                              
                                                        </ul>                                            
                                                    </div>                                          </td>                                        
                                            </tr>                                        
                                            <tr>                                            
                                                <td class="table-status">
                                                    <i class="fa fa-share-alt grey" data-toggle="tooltip" data-placement="top" title="Type de campagne"></i></td>                                            <td>
                                                    <a href="#" data-target="#view_campaign" data-toggle="modal">Ma campagne</a></td>                                            <td>-</td>                                            
                                                <td class="table-status">                                               
                                                    <span class="badge bg-yellow">En cours
                                                    </span>                                            </td>                                            <td>XX/XX/XXXX 24:00</td>                                            <td>XX/XX/XXXX 24:00</td>                                            <td>                                              
                                                    <div class="btn-group">                                              
                                                        <button type="button" class="btn btn-default">Stopper la campagne
                                                        </button>                                              
                                                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">                                                
                                                            <span class="caret">
                                                            </span>                                                
                                                            <span class="sr-only">Toggle Dropdown
                                                            </span>                                              
                                                        </button>                                              
                                                        <ul class="dropdown-menu" role="menu">                                                
                                                            <li>
                                                                <a href="#">
                                                                    <i class="fa fa-font"> |</i>Renommer</a>
                                                            </li>                                                
                                                            <li>
                                                                <a href="#">
                                                                    <i class="fa fa-times"> |</i>Suprimer</a>
                                                            </li>                                                
                                                            <li class="divider">
                                                            </li>                                                
                                                            <li>
                                                                <a href="#">Special link or info</a>
                                                            </li>                                              
                                                        </ul>                                            
                                                    </div>                                          </td>                                        
                                            </tr>                                        
                                            <tr>                                            
                                                <td class="table-status">
                                                    <i class="fa fa-share-alt grey" data-toggle="tooltip" data-placement="top" title="Type de campagne"></i></td>                                            <td>
                                                    <a href="#" data-target="#view_campaign" data-toggle="modal">Ma campagne</a></td>                                            <td>-</td>                                            
                                                <td class="table-status">                                               
                                                    <span class="badge bg-blue">Terminée
                                                    </span>                                            </td>                                            <td>XX/XX/XXXX 24:00</td>                                            <td>XX/XX/XXXX 24:00</td>                                            <td>                                              
                                                    <div class="btn-group">                                              
                                                        <button type="button" class="btn btn-default">Voir les résultats
                                                        </button>                                              
                                                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">                                                
                                                            <span class="caret">
                                                            </span>                                                
                                                            <span class="sr-only">Toggle Dropdown
                                                            </span>                                              
                                                        </button>                                              
                                                        <ul class="dropdown-menu" role="menu">                                                
                                                            <li>
                                                                <a href="#">
                                                                    <i class="fa fa-font"> |</i>Renommer</a>
                                                            </li>                                                
                                                            <li>
                                                                <a href="#">
                                                                    <i class="fa fa-times"> |</i>Suprimer</a>
                                                            </li>                                                
                                                            <li class="divider">
                                                            </li>                                                
                                                            <li>
                                                                <a href="#">Special link or info</a>
                                                            </li>                                              
                                                        </ul>                                            
                                                    </div>                                          </td>                                        
                                            </tr>                                          
                                            </tr>                                    
                                        </tbody>
                                    </table>                                
                                </div>
                                <!-- /.box-body -->                                
                                <div class="box-footer clearfix">                                    
                                    <ul class="pagination pagination-sm no-margin pull-right">                                        
                                        <li>
                                            <a href="#">«</a>
                                        </li>                                        
                                        <li>
                                            <a href="#">1</a>
                                        </li>                                        
                                        <li>
                                            <a href="#">2</a>
                                        </li>                                        
                                        <li>
                                            <a href="#">3</a>
                                        </li>                                        
                                        <li>
                                            <a href="#">»</a>
                                        </li>                                    
                                    </ul>                                                                      
                                </div>                                
                                <div class="clearfix">                                     
                                    <ul class="pull-right">                                        
                                        <a href="#" class="btn-default btn">
                                            <i class="fa fa-th fa-1x"></i> Plus de campagnes</a>                                    
                                    </ul>                                
                                </div>                                                             
                            </div>                                        
                            <!-- ----------------------END FORM LAST CAMPAIGNS-------------------------- -->                                                                                                                               
                        </section>                                                                      
                    </div>                    
                </div>                    
                <div class="tab-pane fade in " id="brouillons">                                                              
                    <!-- ----------------------START BROUILLONS-------------------------- -->                      
                    <div class="">                          
                        <section class=" mgb30 filters-campaigns">                             
                            <form class="bs-example bs-example-form" role="form">                                
                                <div class=" input-group-sm col-md-2">                                  
                                    <input type="text" class="form-control" placeholder="Username">                                
                                </div>                                
                                <div class="input-group-lm  col-md-2">                                                                   
                                    <select class="form-control">                                    
                                        <option>Statuts
                                        </option>                                    
                                        <option>option 2
                                        </option>                                    
                                        <option>option 3
                                        </option>                                    
                                        <option>option 4
                                        </option>                                    
                                        <option>option 5
                                        </option>                                  
                                    </select>                                
                                </div>                                
                                <div class="input-group-lm  col-md-2">                                                                   
                                    <select class="form-control">                                    
                                        <option>Créateur
                                        </option>                                    
                                        <option>option 2
                                        </option>                                    
                                        <option>option 3
                                        </option>                                    
                                        <option>option 4
                                        </option>                                    
                                        <option>option 5
                                        </option>                                  
                                    </select>                                
                                </div>                                
                                <div class="input-group-lm  col-md-2">                                                                   
                                    <select class="form-control">                                    
                                        <option>Type de campagne
                                        </option>                                    
                                        <option>option 2
                                        </option>                                    
                                        <option>option 3
                                        </option>                                    
                                        <option>option 4
                                        </option>                                    
                                        <option>option 5
                                        </option>                                  
                                    </select>                                
                                </div>                                                                 
                                <div class="input-group-lm col-md-2">                                                                                 
                                    <div class="input-group">                                            
                                        <div class="input-group-addon">                                                
                                            <i class="fa fa-calendar"></i>                                            
                                        </div>                                            
                                        <input type="text" id="reservation" class="form-control pull-right">                                        
                                    </div>
                                    <!-- /.input group -->                                
                                </div>                                
                                <div class="input-group">                                     
                                    <button type="submit" class="btn btn-primary">
                                        <i class="fa fa-filter"></i> Filtrer
                                    </button>                                     
                                    <a href="" class="btn btn-default">
                                        <i class="fa fa-save"></i> Exporter</a>                                
                                </div>                                                              
                            </form>                          
                        </section>                     
                    </div>                     
                    <div class="">                          
                        <section class=" ">                                                             
                            <!-- ----------------------START FORM LAST CAMPAINGS-------------------------- -->                                 
                            <div class="box">                                
                                <div class="box-header">                                    
                                    <h3 class="box-title">Liste de mes brouillons</h3>                                                                     
                                </div>
                                <!-- /.box-header -->                                
                                <div class="box-body">                                    
                                    <table class="table table-bordered">                                        
                                        <tbody>
                                            <tr>                                            
                                                <th style="width:40px;">Type
                                                </th>                                            
                                                <th>Nom
                                                </th>                                            
                                                <th>Liste
                                                </th>                                            
                                                <th style="width: 80px">Statut
                                                </th>                                            
                                                <th>Prochain envoi
                                                </th>                                            
                                                <th>Fin de campagne
                                                </th>                                            
                                                <th style="width: 190px">Options
                                                </th>                                        
                                            </tr>                                        
                                            <tr>                                            
                                                <td class="table-type">
                                                    <i class="fa fa-paper-plane-o grey" data-toggle="tooltip" data-placement="top" title="Type de campagne"></i></td>                                            <td>Ma campagne</td>                                            <td>-</td>                                            
                                                <td class="table-status">                                               
                                                    <span class="badge badge-grey">Brouillon
                                                    </span>                                            </td>                                            <td>XX/XX/XXXX 24:00</td>                                            <td>XX/XX/XXXX 24:00</td>                                            <td>                                              
                                                    <div class="btn-group">                                              
                                                        <button type="button" class="btn btn-default">Stopper la campagne
                                                        </button>                                              
                                                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">                                                
                                                            <span class="caret">
                                                            </span>                                                
                                                            <span class="sr-only">Toggle Dropdown
                                                            </span>                                              
                                                        </button>                                              
                                                        <ul class="dropdown-menu" role="menu">                                                
                                                            <li>
                                                                <a href="#">
                                                                    <i class="fa fa-font"> |</i>Renommer</a>
                                                            </li>                                                
                                                            <li>
                                                                <a href="#">
                                                                    <i class="fa fa-times"> |</i>Suprimer</a>
                                                            </li>                                                
                                                            <li class="divider">
                                                            </li>                                                
                                                            <li>
                                                                <a href="#">Special link or info</a>
                                                            </li>                                              
                                                        </ul>                                            
                                                    </div>                                          </td>                                        
                                            </tr>                                        
                                            <tr>                                            
                                                <td class="table-status">
                                                    <i class="fa fa-calendar grey" data-toggle="tooltip" data-placement="top" title="Type de campagne"></i></td>                                            <td>Ma campagne</td>                                            <td>-</td>                                            
                                                <td class="table-status">                                               
                                                    <span class="badge badge-grey">Brouillon
                                                    </span>                                            </td>                                            <td>XX/XX/XXXX 24:00</td>                                            <td>XX/XX/XXXX 24:00</td>                                            <td>                                              
                                                    <div class="btn-group">                                              
                                                        <button type="button" class="btn btn-default">Voir les résultats
                                                        </button>                                              
                                                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">                                                
                                                            <span class="caret">
                                                            </span>                                                
                                                            <span class="sr-only">Toggle Dropdown
                                                            </span>                                              
                                                        </button>                                              
                                                        <ul class="dropdown-menu" role="menu">                                                
                                                            <li>
                                                                <a href="#">
                                                                    <i class="fa fa-font"> |</i>Renommer</a>
                                                            </li>                                                
                                                            <li>
                                                                <a href="#">
                                                                    <i class="fa fa-times"> |</i>Suprimer</a>
                                                            </li>                                                
                                                            <li class="divider">
                                                            </li>                                                
                                                            <li>
                                                                <a href="#">Special link or info</a>
                                                            </li>                                              
                                                        </ul>                                            
                                                    </div>                                          </td>                                        
                                            </tr>                                        
                                            <tr>                                            
                                                <td class="table-status">
                                                    <i class="fa fa-share-alt grey" data-toggle="tooltip" data-placement="top" title="Type de campagne"></i></td>                                            <td>Ma campagne</td>                                            <td>-</td>                                            
                                                <td class="table-status">                                               
                                                    <span class="badge badge-grey">Brouillon
                                                    </span>                                            </td>                                            <td>XX/XX/XXXX 24:00</td>                                            <td>XX/XX/XXXX 24:00</td>                                            <td>                                              
                                                    <div class="btn-group">                                              
                                                        <button type="button" class="btn btn-default">Stopper la campagne
                                                        </button>                                              
                                                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">                                                
                                                            <span class="caret">
                                                            </span>                                                
                                                            <span class="sr-only">Toggle Dropdown
                                                            </span>                                              
                                                        </button>                                              
                                                        <ul class="dropdown-menu" role="menu">                                                
                                                            <li>
                                                                <a href="#">
                                                                    <i class="fa fa-font"> |</i>Renommer</a>
                                                            </li>                                                
                                                            <li>
                                                                <a href="#">
                                                                    <i class="fa fa-times"> |</i>Suprimer</a>
                                                            </li>                                                
                                                            <li class="divider">
                                                            </li>                                                
                                                            <li>
                                                                <a href="#">Special link or info</a>
                                                            </li>                                              
                                                        </ul>                                            
                                                    </div>                                          </td>                                        
                                            </tr>                                        
                                            <tr>                                            
                                                <td class="table-status">
                                                    <i class="fa fa-share-alt grey" data-toggle="tooltip" data-placement="top" title="Type de campagne"></i></td>                                            <td>Ma campagne</td>                                            <td>-</td>                                            
                                                <td class="table-status">                                               
                                                    <span class="badge badge-grey">Brouillon
                                                    </span>                                            </td>                                            <td>XX/XX/XXXX 24:00</td>                                            <td>XX/XX/XXXX 24:00</td>                                            <td>                                              
                                                    <div class="btn-group">                                              
                                                        <button type="button" class="btn btn-default">Voir les résultats
                                                        </button>                                              
                                                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">                                                
                                                            <span class="caret">
                                                            </span>                                                
                                                            <span class="sr-only">Toggle Dropdown
                                                            </span>                                              
                                                        </button>                                              
                                                        <ul class="dropdown-menu" role="menu">                                                
                                                            <li>
                                                                <a href="#">
                                                                    <i class="fa fa-font"> |</i>Renommer</a>
                                                            </li>                                                
                                                            <li>
                                                                <a href="#">
                                                                    <i class="fa fa-times"> |</i>Suprimer</a>
                                                            </li>                                                
                                                            <li class="divider">
                                                            </li>                                                
                                                            <li>
                                                                <a href="#">Special link or info</a>
                                                            </li>                                              
                                                        </ul>                                            
                                                    </div>                                          </td>                                        
                                            </tr>                                                                                                                          
                                            </tr>                                    
                                        </tbody>
                                    </table>                                
                                </div>
                                <!-- /.box-body -->                                
                                <div class="box-footer clearfix">                                    
                                    <ul class="pagination pagination-sm no-margin pull-right">                                        
                                        <li>
                                            <a href="#">«</a>
                                        </li>                                        
                                        <li>
                                            <a href="#">1</a>
                                        </li>                                        
                                        <li>
                                            <a href="#">2</a>
                                        </li>                                        
                                        <li>
                                            <a href="#">3</a>
                                        </li>                                        
                                        <li>
                                            <a href="#">»</a>
                                        </li>                                    
                                    </ul>                                
                                </div>                                
                                <div class="clearfix">                                     
                                    <ul class="pull-right">                                        
                                        <a href="#" class="btn-default btn">
                                            <i class="fa fa-align-justify fa-1x"></i> Plus de campagnes</a>                                    
                                    </ul>                                
                                </div>                            
                            </div>                                        
                            <!-- ----------------------END FORM LAST CAMPAIGNS-------------------------- -->                                                                                                                               
                        </section>                                                                      
                    </div>                                         
                    <!-- ----------------------END BROUILLONS-------------------------- -->                                         
                </div>                    
            </div>               
        </section>   
    </div>
</div>
