<?php
/**
 * stats.phtml
 *
 * LICENCE
 *
 * PHP Version 5.3
 *
 * L'ensemble de ce code relève de la législation française et internationale
 * sur le droit d'auteur et la propriété intellectuelle. Tous les droits de
 * reproduction sont réservés, y compris pour les documents téléchargeables et
 * les représentations iconographiques et photographiques. La reproduction de
 * tout ou partie de ce code sur quelque support que ce soit est formellement
 * interdite sauf autorisation écrite émanant de la société DIGITALEO.
 *
 * @category Digitaleo
 * @package  Application.Modules.Frontoffice.Views.Campaign
 * @author   Digitaleo <developpement@digitaleo.com>
 * @license  http://www.digitaleo.net/licence.txt Digitaleo Licence
 * @link     http://www.digitaleo.net
 */
?>

<script type='text/javascript'>

    $(function () {
        $("#stat-tabs").tabs({
            selected: 'Etape 1',
            ajaxOptions: {
                error: function (xhr, status, index, anchor) {
                    $(anchor.hash).html('<?php echo $this->translate('Cannot load this tab'); ?>');
                },
                beforeSend: function (e, ui) {
                    $('#ajax-loading').show();
                }
            },
            cache: true,
            load: function (e, ui) {
                $('#ajax-loading').hide();

                $.each($('.stat-performance table.liste tr'), function () {
                    if ($(this).children('td').children('a').size() > 0) {
                        $(this).css('cursor', 'pointer');
                    }
                });
            },
            select: function (e, ui) {
            }
        });
    });

<?php $this->jQuery()->onLoadCaptureStart(); ?>

    /*
     * Sauvegarde an AJAX du commentaire de la campagne
     */
    $('#comment').change(function () {
        $('#ajax-loading').show();
        var params = {};
        params['campaignId'] = <?php echo $this->campaign->id ?>;
        params['comment'] = $('#comment').val();
        $.post(
                "<?php echo $this->href('ajax-save'); ?>",
                params,
                function (data) {
                    $('#ajax-loading').hide();
                }
        );
    });

    /* change */
    $('.stat-performance table.liste tr').live('click', function () {
        /* si il n'y a qu'un seul lien dans toute la ligne, un clic sur la ligne causera un clic sur le lien */
        var link = $(this).children('td').children('a');
        if (link.size() > 1) {
            document.location.href = link.last().attr('href');
        } else if (link.size() == 1) {
            document.location.href = link.attr('href');
        }
    });
<?php if ($this->hasAccess('exportContact')) : ?>
        $('#export-archive').on('click', function () {
            $("#export-archive-form").remove('input');
            $('*[data-highcharts-chart]').each(function (index, element) {
                $("#export-archive-form").append('<input type="hidden" name="' + $(element).prop('id') + '">');
                $("#export-archive-form").children('[name="' + $(element).prop('id') + '"]')
                        .val($(element).highcharts().getSVG());
            });
            $("#export-archive-form").submit();
            _gaq.push(['_trackEvent', 'Campaigns', 'Export', 'ResultsZIP']);
        });
<?php endif; ?>
    $('#export-pdf').on('click', function () {
        $("#export-pdf-form").remove('input');
        $('*[data-highcharts-chart]').each(function (index, element) {
            $("#export-pdf-form").append('<input type="hidden" name="' + $(element).prop('id') + '">');
            $("#export-pdf-form").children('[name="' + $(element).prop('id') + '"]')
                    .val($(element).highcharts().getSVG());
        });
        $("#export-pdf-form").submit();
        _gaq.push(['_trackEvent', 'Campaigns', 'Export', 'ResultsPDF']);
    });
<?php $this->jQuery()->onLoadCaptureEnd(); ?>

</script>

<section class="content-header">
    <i class="fa fa-users fa-2x left mgt5 grey"></i>
    <h1><?php echo ucfirst($this->translate('campaign details')) ?></h1>
</section>

<section class="left-col">
    <div class="row center pdb20">
        <div class="col-xs-12 col-sm-4">
            <div class="bglightgrey pd10">
                <label><?php echo ucfirst($this->translate('name')); ?></label>
                <p><b><?php echo $this->truncate($this->campaign->name, 40); ?>
                    <?php if (Service_Api_Object_Campaign::STATUS_CANCELED == $this->campaign->status) : ?>
                        <?php echo $this->translate($this->campaign->status); ?>
                    <?php endif; ?></b></p>
            </div>
        </div>
        <div class="col-xs-12 col-sm-4">
            <div class="bglightgrey pd10">
                <label><?php echo ucfirst($this->translate('list of contacts')); ?></label>
                <p><b><?php
                        if ($this->listName) {
                            echo $this->truncate($this->listName, 40);
                        } else {
                            echo ucfirst($this->translate('None selected list'));
                        }
                        ?></b></p>
            </div>
        </div>
        <div class="col-xs-12 col-sm-4">
            <div class="bglightgrey pd10">
                <label><?php echo ucfirst($this->translate('number of contacts')); ?></label>
                <!--<p><?php echo $this->listSize ?></p>-->
                <p><b><?php echo $this->listCount ?></b></p>
            </div>
        </div>
    </div>
    <div class="row pdb20">
        <div class="comments">
            <?php if (!is_null($this->advice)) : ?>
                <div class="col-xs-12"><label><?php echo ucfirst($this->translateAffiliate('advice for affiliates')); ?></label></div>
                <div class="col-xs-12"><?php echo nl2br($this->advice); ?></div>
            <?php endif; ?>
            <div class="col-xs-12"><label><?php echo ucfirst($this->translate('comment')); ?></label></div>
            <div class="col-xs-12"><textarea id='comment' style="min-height:50px;" class="form-control"><?php echo $this->campaign->comment ?></textarea></div>
        </div>
    </div>
    <div class="top-left-col">
        <ul class="nav nav-tabs nav-pills">
            <div class="content-left-col">
                <div id='stat-tabs'>
                    <ul>
                        <?php
                        foreach ($this->steps as $key => $step) :
                            $url = $this->href('stat-ajax', array('stepId' => $step->id, 'campaignId' => $this->campaign->id,
                                'isRental' => $this->isRental));
                            ?>
                            <li>
                                <a href="<?php echo $url; ?>"><?php echo ucfirst($this->translate('step')); ?>&nbsp;
                                    <?php echo ($key + 1); ?></a>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </div>
        </ul>


        <div class="bottom-content-buttons">
            <ul>
                <li>
                <buttton class="btn btn-default" onclick="window.history.back();"><i class="fa fa-angle-double-left"></i> <?php echo ucfirst($this->translate('back')); ?></buttton>
                </li>
                <?php if ($this->hasAccess('contactManagement')) : ?>
                    <?php if (isset($this->isMock) && $this->isMock) : ?>
                        <li>
                            <button class="disable btn btn-primary"><i class="fa fa-upload"></i> <?php echo ucfirst($this->translate('complete export')); ?></button>
                        </li>
                    <?php else : ?>
                        <?php if ($this->hasAccess('exportContact') && !$this->isRental) : ?>
                            <li>
                                <button id="export-archive" class="btn btn-primary"><i class="fa fa-upload"></i> <?php echo ucfirst($this->translate('complete export')); ?></button>
                            </li>
                        <?php endif; ?>
                    <?php endif; ?>
                <?php endif; ?>
                <li>
                    <button id="export-pdf" class="btn btn-primary"><i class="fa fa-upload"></i> <?php echo ucfirst($this->translate('export pdf')); ?></button>
                </li>
            </ul>
            </ul>
            <?php if ($this->hasAccess('exportContact')) : ?>
                <form name="export-archive-form"
                      id="export-archive-form"
                      style="display:none"
                      method="POST"
                      action="<?php
                      echo $this->href('generate-stats-archive', array('campaignId' => $this->campaign->id))
                      ?>">
                </form>
            <?php endif; ?>
            <form name="export-pdf-form"
                  id="export-pdf-form"
                  style="display:none"
                  method="POST"
                  action="<?php
                  echo $this->href('complete-stats', array('format' => 'pdf', 'campaignId' => $this->campaign->id))
                  ?>">
            </form>
        </div>
    </div>
</section>
